### ISSUE TITLE
What should I import to the database

### ISSUE THREAD

**Issue by shimaimani** [huda-lab/qetch#3]
What should I exactly import to the database in order to see the data sets? because the dropdown menu does not work for me.

**Comment by miromannino** [comment]
There is a file _Datasets/psdb.txt_ with instructions on how to install the database and to initialise it.

Here the file in github
[https://github.com/dtl-nyuad/qetch/blob/master/Datasets/psdb.txt](https://github.com/dtl-nyuad/qetch/blob/master/Datasets/psdb.txt)

After that you can load the data. For that you need to configure the db connection settings in this file: _Server/config.json_ and then execute _Datasets/utils/load_all.sh_ to dowload some datasets we used too. If you want to download your own datasets anyway is easy, just by reading the load_all script you can quickly understand how to load others.

**Comment by shimaimani** [comment]
Thank you so much. It is working now :)

I really appreciate your response.

**Comment by shimaimani** [comment]
Hi Miro,

Thank you so much for all of your help.
I am trying to upload a data which has a length of 13,000 data points but
the app is irresponsive. I was wondering if there is any limit on the
length of time series?

Best,
Shima

**Comment by miromannino** [comment]
Hello shima,

I am not sure about the exact problem, but it might be that with this dataset the d3 line chart takes too long to render? (but this also depends on your browser or machine configuration).

If you would like I can try to debug/profile what could be the problem if you can share via email the dataset.

Best,

Miro

**Comment by shimaimani** [comment]
Thank you so much Miro,

I will change my browser and use another machine first to see if I can
solve the problem.

Thanks,
Best,
Shima

**Comment by liyan0427** [comment]
> There is a file _Datasets/psdb.txt_ with instructions on how to install the database and to initialise it.
> 
> Here the file in github
> https://github.com/dtl-nyuad/qetch/blob/master/Datasets/psdb.txt
> 
> After that you can load the data. For that you need to configure the db connection settings in this file: _Server/config.json_ and then execute _Datasets/utils/load_all.sh_ to dowload some datasets we used too. If you want to download your own datasets anyway is easy, just by reading the load_all script you can quickly understand how to load others.

Hi Miro,

Can you please explain how to configure the db connection settings using file: Server/config.json? Thank you :)

**Comment by miromannino** [comment]
Hello @liyan0427 ,

The configuration file just provides the connection url to the database, following this format:

    postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]

you can find examples online about connection URL too.

For example mine just was:

    postgresql://username:password@localhost/qetch

**Comment by liyan0427** [comment]
Hi @miromannino, thank you for your reply! 
May I just clarify - so I need to create my own user and password in the database, and then configure using the URL using my info right? I still have permission denied issues and couldn't grant privileges to my own created account. Can you please advise me on what to do? Sorry about all the naive questions as I am really new to this :)

**Comment by miromannino** [comment]
Yes exactly it is the database you like and user and password you like, then you just need to copy and paste these info in the config file. 

Make sure your username can access in the database. To double-check you can try from the console with: 

    psql -d yourDBName -U yourUserName

If that works then you just need :

    postgresql://yourUserName:yourUserPassword@localhost/yourDBName

I hope it helps!

**Comment by LiuC425** [comment]
Hi Miro,

Thank you for your work, its inspiring!

I have two questions:
1. I've tried hosting the expressjs project on my gcp instance, however, with data loaded by loaddata.sh or dump.sql(they should give me the same results yes?). 
2. I see data in my db, but the dropdown menu still doesn't work. (I suspect the db is not connected when I npm start the code.) I think somewhere I need to call the "datasets" or "queries" service in the routers to make the datasets.js to connect to the database, but I don't think thats how it works. Any advice?

Cheers

**Comment by miromannino** [comment]
Hello @LiuC425,

Thank you! 

For the database you can load either way. (2) The empty dropdown it might just be that the server can't access to the database, but somewhere in the server's console there should be an error that the server can't connect to the database. There is a file config.json in the root which has a connection string to the DB, but that is for my personal server and surely you might need to change that.

I hope it helps! Let me know.

**Comment by LiuC425** [comment]
Hi Miro @miromannino ,

Thanks for getting back to me, I've changed config.json, and I've changed everywhere that has "miro" to "postgres"(as I have created a user called postgres). This should work yeah? But mine doesn't. For the record, test_connection.js and test_db_loader.js works. 

I'm thinking of pulling down a new repo and create a user called miro so I don't need to change other stuff : )

Cheers

**Comment by miromannino** [comment]
Hello @LiuC425,

the connection string you find in these two test files you mentioned is different than the one in config.json. Might be because of it. But surely creating a user "miro" would do the trick without you need to change any configuration file :)

**Comment by miromannino** [comment]
Hello @LiuC425 ,

after inspecting I noticed that a new version of the pg library wasn't connecting to the database even with right credentials and it wasn't throwing any error either (just the callback wasn't called), making the load a silent fail.

You might want to clone the project again and follow the updated instructions in the [README.md](https://github.com/huda-lab/qetch/blob/master/README.md). 

This time instead of **miro** as user I tried with **qetchdb_user** and **qetchdb_user_password** as password, but you can change these as you want as usual.

To make it less confusing the configuration moving the [configuration file](https://github.com/huda-lab/qetch/blob/master/config.json) in the root so both the database loading part and the server part works with that configuration.

I hope it helps
