### ISSUE TITLE
Endless time series loading 

### ISSUE THREAD

**Issue by abdelouahab1** [huda-lab/qetch#4]
I encountered an issue loading time series, I imported the time series as [explained here](https://github.com/huda-lab/qetch/issues/3). The dropdown menu works for me and I could see the time series list. However, any time series I chose takes forever to load and loading never ends, I waited over 3 hours for varying time series. 

Am I missing something?

**Comment by miromannino** [comment]
I think the explanation is that there is some error while loading, most likely related to the browser.
Can you open the browser console to show if there is any error?

The time series should load in seconds.

**Comment by abdelouahab1** [comment]
Hello and thank you for your response!

Indeed! The following error is thrown: 

```
angular.js:12808 TypeError: Cannot read property 'y' of undefined
    at Object.dataHeight (dataUtilsAPI.js:119)
    at Object.smoothData (dataUtilsAPI.js:34)
    at Object.updateDataForDisplaySize (datasetAPI.js:228)
    at datasetAPI.js:90
    at async.min.js:1
    at o (async.min.js:1)
    at async.min.js:1
    at datasetAPI.js:85
    at angular-resource.js:653
    at angular.js:15122
```

**Comment by abdelouahab1** [comment]
It was an username conflict. The name of the author "mido" is present in other files besides the config.json file. I searched all the appearances of the label "mido" and replaced it by my username, the problem was solved.
